name: globalvossen
favicon: null
layout_spectrum: 0.4204556541517377
typography_spectrum: 0.7460553613491356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3606340903788805
  lightness: 0.2960193871986121
  saturation: 0.07385661569423974
  rhythmicContrast: 0.6427213686984032
purpose: []
